disabled_rules:
- trailing_whitespace
- unused_closure_parameter
- unused_optional_binding
- redundant_string_enum_value
- empty_count

opt_in_rules:
- empty_string

excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib

line_length:
    warning: 500
    error: 500
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true

function_body_length:
    warning: 300
    error: 500

function_parameter_count:
    warning: 12
    error: 12

type_body_length:
    warning: 300
    error: 500

file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true

cyclomatic_complexity:
    warning: 15
    error: 25

variable_name:
  max_length:
    warning: 45
    error: 60
  min_length:
    warning: 1

reporter: "xcode"

